services:
  backend:
    build:
      context: ./
    ports:
      - 4567:4567
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
